<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Tessera.Nexus.AI.Application\Tessera.Nexus.AI.Application.csproj" />
    <ProjectReference Include="..\Tessera.Nexus.AI.Infrastructure\Tessera.Nexus.AI.Infrastructure.csproj" />
    <ProjectReference Include="..\Tessera.Nexus.AI.Metadata\Tessera.Nexus.AI.Metadata.csproj" />
    <ProjectReference Include="..\Tessera.Nexus.AI.Security\Tessera.Nexus.AI.Security.csproj" />
    <ProjectReference Include="..\Tessera.Nexus.AI.Audit\Tessera.Nexus.AI.Audit.csproj" />
    <ProjectReference Include="..\Tessera.Nexus.AI.Shared\Tessera.Nexus.AI.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
