namespace Tessera.Nexus.AI.Application.DTOs;

/// <summary>
/// Result returned from the AI query generation pipeline.
/// </summary>
public sealed class QueryResponse
{
    /// <summary>
    /// Original user question.
    /// </summary>
    public string UserQuestion { get; set; } = string.Empty;

    /// <summary>
    /// Prompt sent to the model.
    /// </summary>
    public string GeneratedPrompt { get; set; } = string.Empty;

    /// <summary>
    /// SQL generated by the model.
    /// </summary>
    public string GeneratedSql { get; set; } = string.Empty;

    /// <summary>
    /// Indicates overall success.
    /// </summary>
    public bool Success { get; set; }

    /// <summary>
    /// Indicates whether SQL validation succeeded.
    /// </summary>
    public bool SqlValidated { get; set; }

    /// <summary>
    /// Number of rows returned by execution.
    /// Keep this property name as RowCount.
    /// The SQL Server naming issue only applies to QueryHistory table columns,
    /// not application DTOs.
    /// </summary>
    public int? RowCount { get; set; }

    /// <summary>
    /// Total processing duration.
    /// </summary>
    public long ElapsedMilliseconds { get; set; }

    /// <summary>
    /// Error message when processing fails.
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// Serialized execution result payload.
    /// </summary>
    public string? ResultJson { get; set; }

    /// <summary>
    /// UTC timestamp when the request completed.
    /// </summary>
    public DateTime ProcessedUtc { get; set; }
}