namespace Tessera.Nexus.AI.Application.DTOs;

/// <summary>
/// Represents the result of an AI-generated query request.
/// </summary>
public sealed class QueryResponse
{
    /// <summary>
    /// Original user question.
    /// </summary>
    public string UserQuestion { get; set; } = string.Empty;

    /// <summary>
    /// Prompt generated by PromptBuilder.
    /// </summary>
    public string GeneratedPrompt { get; set; } = string.Empty;

    /// <summary>
    /// SQL generated by the AI model.
    /// </summary>
    public string GeneratedSql { get; set; } = string.Empty;

    /// <summary>
    /// Indicates whether processing succeeded.
    /// </summary>
    public bool Success { get; set; }

    /// <summary>
    /// Error message when processing fails.
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// UTC timestamp when the request was processed.
    /// </summary>
    public DateTime ProcessedUtc { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Processing duration in milliseconds.
    /// </summary>
    public long ElapsedMilliseconds { get; set; }

    /// <summary>
    /// Indicates whether the generated SQL passed validation.
    /// </summary>
    public bool SqlValidated { get; set; }

    /// <summary>
    /// Row count returned by query execution.
    /// Populated later when execution is implemented.
    /// </summary>
    public int? RowCount { get; set; }

    /// <summary>
    /// Query results serialized as JSON.
    /// Populated later when execution is implemented.
    /// </summary>
    public string? ResultJson { get; set; }
}